### ISSUE TITLE
FOLLOW UP: Open Work Item Detail View from Card View

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#205]
- Contact Dev, let them know you are their contact person for questions
- Check in with them, on an a periodic as needed basis throughout the sprint
- Assure that this functionality is demoed and meets specifications in the original UX design.

GitHub:

UX
???

Dev
https://github.com/fabric8io/fabric8-planner/issues/888

**Comment by SMahil** [comment]
Below are the screenshots for current implementation what we have

<img width="1079" alt="screen shot 2017-03-01 at 11 28 58 am" src="https://cloud.githubusercontent.com/assets/10396359/23447680/9094e17c-fe72-11e6-8e52-460a0e79fbc3.png">
<img width="1151" alt="screen shot 2017-03-01 at 11 29 12 am" src="https://cloud.githubusercontent.com/assets/10396359/23447681/9095227c-fe72-11e6-885d-5ac254135c80.png">

@Essjaysee Let me know if any changes required

KNOWN ISSUE: detail page is aligned to header instead of content area. Once the integration is done will fix that

**Comment by Essjaysee** [comment]
Hi @SMahil!  Thanks for posting these.  It's coming along really nicely.  Just a couple things I noticed:

- The kebab icon (the one with the three dots) should be dark grey (363636)
- Assuming that these are the default states we are providing and not ones that you created, "new," "open," "in progress," and so on should have their first letters capitalized
- When a work item has no assignee, the text on the detail view should say "None" and be styled without italics and be blue (0088ce)
- The caret on the relationship links bar should be pointing right because it's collapsed

**Comment by catrobson** [comment]
@Essjaysee anything we need here or ready to close?

**Comment by Essjaysee** [comment]
@catrobson It's ok by me to close it.
