### ISSUE TITLE
VISUALS (SPECS): Map Statuses & Types to iconography + create iconography (Part 1 of 2)

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#215]
Continuation of work started in ALM - [VISUALS: Define Draft of Default Icons for Work Items](https://github.com/fabric8io/fabric8-ux/issues/64) & [VISUALS: Vet & Finalize Default Icons](https://github.com/fabric8io/fabric8-ux/issues/104)

* Gather list of all Work Item Type icons, from the Issue Tracking & Scrum process templates 
* Map any existing icons to the statuses (We already have Epic, Bug)
* Create any new icons for the other statuses (Working on getting definitions, will add them here)

Icons needed (according to Todd, 2 templates still outstanding). 
See "Type 1" column in tabs: 
* "Issue Tracking WILTs"
* "SCRUM WILTs":
https://docs.google.com/a/redhat.com/spreadsheets/d/1iQ3MBitXy5zWAvxWzHQKtXuv5SWs_uUCQvrqngfm5K8/edit?usp=sharing

VC's
* All Work Item Type icons have been accounted for
* All icons have been approved by stakeholders
* Icons are in a format for consumption by development

**Comment by mindreeper2420** [comment]
@jryhanyc I received a request from the Dev team this evening for a list of all of the icons, what they belong to and their CSS classes. Would you be able to fold that request into this work? The request issue is here: https://github.com/fabric8io/fabric8-ux/issues/294.

It was also pointed out that in the first pass of the Work Item Status icons, the checkmark was used for 'Done', but is also used as the icon for the Confirm Button. Can you verify that that is the correct usage? Thanks!

**Comment by bdellasc** [comment]
@jryhanyc I just added the current state of the world in the [294-Icon Documentation comment thread](https://github.com/fabric8io/fabric8-ux/issues/294). This list was derived from e-mail threads and cross-referencing those with the spreadsheet. I took a first stab at some definitions for a few of the Work Item Types, but need feedback to be sure they're accurate. A little progress, but nothing that will let you start the Work Item Types work yet. I'll update that list as things get verified.

**Comment by bdellasc** [comment]
**Rollup of current (Unconfirmed) types & states:** 

*Notes:
- "/" means the same icon could be used for both
- Text in "()" are definitions - some need verification

**Work Item Types (design handled by @jryhanyc)**

Confirmed icons that are currently missing:
- Feature
- Issue (Confirmed by Max: something that has been observed to either be a problem or missing thing in the already running system?)
- Papercut (Pending definition confirmation from Todd: "trivial to fix, but annoying bugs")
- Scenario (Confirmed: a specific defined interaction/sequence of interactions with a system to achieve a given goal)
- Task (Confirmed by Max: something performed in order to complete a work item where a work item can be a story, feature, backlog item, etc.)

Currently have proposed Icons:
- Bug
- Epic
- Experience
- Fundamental
- Product Backlog Item (Not sure if Issue can also use this)
- Value Proposition


**States (design handled by @bdellasc)**

Icons in bold are currently missing:
- New
- Approved (Confirmed: approved by PM or Ready-Ready, and can planed or handed off the the team.)
- Committed (Confirmed: team has planned to work on it)
- Active/In Progress
- Resolved/Done 
- Closed (Confirmed: verified and meets the Definition of Done)**
- Removed (Leave name as is for now)**

**Comment by catrobson** [comment]
@bdellasc can you link in what you demoed today?

**Comment by bdellasc** [comment]
Icons verified with Todd, and will be tested:

https://redhat.invisionapp.com/share/N8AZVB493
