### ISSUE TITLE
Visual Styling of the Login Screen (Discussion)

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#34]
This is with reference https://github.com/almighty/almighty-core/issues/304

We wanted to confirm that
- We will be following https://redhat.invisionapp.com/share/8K8FFFIEC#/screens for the login work flow
- For the login screen, can you confirm, if we can use the PatternFly login screen as a visual reference http://www.patternfly.org/pattern-library/application-framework/login-page/#_

Can you confirm the below changes that need to be done to the PatternFly login screen for ALM:
- Remove username, password, remember username option, and forgot password link
- Remove PatternFly logo
- Remove the PatternFly application description text
- We will rename the login button as **Sign in with GitHub**
- We will rename PATTERNFLY Enterprise Application as ALMIGHTY

Questions:
- Does PatternFly have a non-black login screen option?
- Any suggestions on how we can enhance the login page, as it looks very plain after removing so many elements.
  ![almlogin](https://cloud.githubusercontent.com/assets/1892722/19028552/edd081e4-895a-11e6-991e-09b72c10fbd2.png)

**Comment by mindreeper2420** [comment]
@henqian @bdellasc

**Comment by bdellasc** [comment]
For Red Hat products, brand requirements drive our login screens. 

We fold in brand elements via the background images and keep the styling very clean and simple. In the example I've attached, we typically have the corner background images, product name, login fields, "remember me" checkbox and an area for an optional description of the product.

In the case of a launch screen that just brings you to a GitHub login, maybe we just have the following elements from the example:
- Corner background images
- Application Demo Title
- The description where the login fields would normally sit (moving it to the left of where it is in the example)
- Remove the vertical line separating the login fields & Description
- Button to launch Git login

Here is the page with the reference HTML & Angular code:
https://www.patternfly.org/pattern-library/application-framework/login-page/#_code

The brand-specific login bg image assets are here:
[https://github.com/patternfly/rcue/tree/master/dist/img](https://github.com/patternfly/rcue/tree/master/dist/img)
![rcue-login_2016-10-03](https://cloud.githubusercontent.com/assets/17882357/19048582/f490a670-8974-11e6-93a3-a6d2cb69f0b8.png)

**Comment by sanbornsen** [comment]
I think we have plan for github login only as of now.

**Comment by joshuawilson** [comment]
@bdellasc why did you link to https://github.com/patternfly/rcue ? What should we get from there?

Should we just use this view of PF login with the changes you suggest as our login UX or is there a UX design going to be created in invision?

**Comment by joshuawilson** [comment]
@bdellasc please be aware that we are not able to use any existing PF code, only the styles. We are working toward PF4.

**Comment by bdellasc** [comment]
The only major difference between the PatternFly and RCUE styling is the imagery we use for the corners of the login screen and the inclusion of the Red Hat logo. Those images are driven by Red Hat brand and can be found in that repository. Because the product-related images are for Red Hat specifically, we separate them out from PatternFly (which is where we get all of the other styling around UI elements, etc). Because we separate them out, that repository is private and you just need to reach out to the PF folks (who are with Red Hat) and ask to get access to those artifacts.

If including those images cannot be achieved right now, it's something we should aim for later on in the development of the login screen. I wanted to just make folks aware of the recommended styling for Red Hat products :-). 

Will there be actual login fields on this screen at some point? Or will the demo always just link off to Git?

**Comment by nimishamukherjee** [comment]
@bdellasc currently we are integrating only Login via Git.
In the future, the user can sign up and login their using username and password. There would be options to sign in using various social accounts. The user should be able to user their Red Hat Developer account also.
