### ISSUE TITLE
Question: Do we need "Assign to me"

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#373]
We use the text "Assign to me" to refer to the logged in user.
This appears in:
1. Work item detail view's assignee field
2. List view/ board view - as a filter option for the user filter.

Do we use the logged in user's name instead of "Assign to me"?

**Comment by catrobson** [comment]
@nimishamukherjee "Assign to me" should be the call to action if something is not assigned to anyone and the user wants to quickly assign it to themselves.  

Once it is assigned, the logged in username should be shown on the work item, the list view/board view, and on the filters rather than "assigned to me".

Here are detailed specs for these different areas:

*Work item details*  
We show as "unassigned", and when you click into edit the currently logged in user is shown at the top of the list with (me): https://redhat.invisionapp.com/share/VK9L3RIUG#/209560413_A-0100-Assign_User_-_Unassigned  Once assigned it just shows username: https://redhat.invisionapp.com/share/VK9L3RIUG#/209560402_A-0100-Assign_User_-_Assigned

*Filters*
I think our specification is not correct here as it exists - https://redhat.invisionapp.com/share/56AH8F1XM#/219275641_Filters_Specifications

Here we should probably have the filter dropdown when filtering on Assignee allow the user to choose their username or "unassigned" at the top before listing all users.  We could use something similar to what we use in Work Item Details for this purpose.  I'll update the wireframes today to reflect this and post back here.

**Comment by catrobson** [comment]
@nimishamukherjee I've updated the filters specification to be more explicit in how we handle this situation:  https://redhat.invisionapp.com/share/56AH8F1XM#/219275641_Filters_Specifications

Please let me know if you have any other questions about it!

**Comment by nimishamukherjee** [comment]
Thanks @catrobson
