### ISSUE TITLE
LAUNCH - Visual design & Content Review

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#403]
launch.openshift.io is also be "released" at Summit, and needs to attention to align it to OpenShift.io the best we can for now, especially the first page.

It can also be viewed at launch-stage.openshift.io.  

Looking for visual design pass on homepage.  Here's my notes on what we discussed with Dev team and I noticed as fixes needed:
![launchpad_homepage_cat snotes](https://cloud.githubusercontent.com/assets/3739227/25413309/76b15cc6-29f7-11e7-9ced-26384920f2b6.png)

Looking for some content review, especially for the buttons, on Step 1:
![image](https://cloud.githubusercontent.com/assets/3739227/25413340/abe2a012-29f7-11e7-96f0-f3f28b883b36.png)

Looking for visual design recommendation on how to tie the text to the selection on Step 2, and to consider what the header and footer should look like within the wizard experience:
![image](https://cloud.githubusercontent.com/assets/3739227/25413374/e3f4b544-29f7-11e7-81e7-0aa6ad6704d9.png)

Looking for slight reorganization of the various states that occur on Step 5 - this one might require seeing it working or talking through it with me:
![image](https://cloud.githubusercontent.com/assets/3739227/25413442/5b0978e0-29f8-11e7-89cc-76572ed357df.png)

**Comment by catrobson** [comment]
@jryhanyc @Essjaysee I hope the three of us might be able to sit down tomorrow and knock this out together with the information and assets we all have around the various parts of this.

**Comment by ALRubinger** [comment]
@edewit @gastaldi @quintesse FYI - UXD team review incoming.  Let's be sure to get them whatever they need. :)

**Comment by ALRubinger** [comment]
@catrobson RE: the footer - we have been advised by legal to remove the "All policies" link currently on openshift.io; I imagine they'll soon be talking to y'all about doing the same.

**Comment by ALRubinger** [comment]
Reference; issue to which we've made some commits already: openshiftio/launchpad-frontend#89

**Comment by catrobson** [comment]
@ALRubinger - can you align the header and footer to OpenShift.io marketing page?  Don't include the Red Hat Developer Program link (we're removing that too soon) nor the status icon, but otherwise use same styling.  This should remove the top PatternFly blue bar as well, going to just a wider bar on top w/ OpenShift.io branding and username info.  Footer should be followed exactly.

Can be found here:  https://github.com/openshiftio/www.openshift.io

**Comment by edewit** [comment]
@catrobson how do we make the "vert.x" "spring boot" and "widlfy swarm" "buttons" look less like buttons? I only put the white background there because most of the logos are very dark and need some contrast.

For the background image, we use the same one as openshift.io only we stretch it so that we don't get a white "bar" in the bottom.

Create a [PR](https://github.com/openshiftio/launchpad-frontend/pull/101 for footer and header to use the same html and css, only thing strange is that our icon still looks different
![screenshot from 2017-04-27 11-09-16](https://cloud.githubusercontent.com/assets/51133/25476290/fedd49b4-2b39-11e7-982f-c3d7ecb1c027.png)
)

**Comment by mindreeper2420** [comment]
@edewit I checked your package.json file and it looks like you are using an older version of PatternFly? OSio is using 3.21, which has a newer set of icons.

**Comment by catrobson** [comment]
@edewit - @jryhanyc is working out some visual design suggestions for the vert.x, spring boot, etc on that homepage.

**Comment by catrobson** [comment]
Updated visual, terminology, and UX suggestions here:  https://redhat.invisionapp.com/share/2DBHCI7X9#/screens/231156312

**Comment by gastaldi** [comment]
That is really cool. @catrobson 

When "Launch on Openshift Online" is clicked, the UI may also receive errors from the backend (like, User didn't associate the Github/Openshift tokens, Quota limit was reached, etc..). Maybe it would be nice to have one screen showing that?

**Comment by catrobson** [comment]
@jryhanyc - would you be able to do an example error state?  @gastaldi - would these errors happen by step, or do you think it would be more of an overall error?

**Comment by gastaldi** [comment]
These errors may happen by step, when pushing to github or openshift for
example

Em 27 de abr de 2017 22:17, "catrobson" <notifications@github.com> escreveu:

@jryhanyc <https://github.com/jryhanyc> - would you be able to do an
example error state? @gastaldi <https://github.com/gastaldi> - would these
errors happen by step, or do you think it would be more of an overall error?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fabric8io/fabric8-ux/issues/403#issuecomment-297881475>,
or mute the thread

**Comment by jryhanyc** [comment]
@gastaldi We have two designs for an error state. #1 should be used if the user needs to start the whole process over, #2 should be used if they actually can just retry that one step where the error occured. 
[Mockups are in InVision](https://redhat.invisionapp.com/share/BGBHZ8FPK#/231315304_Screen_Shot_2017-04-28_At_10-28-24_AM)

**Comment by gastaldi** [comment]
Great, thanks, @jryhanyc can you merge your mockups with https://redhat.invisionapp.com/share/2DBHCI7X9?

**Comment by gastaldi** [comment]
For now we don't support retrying just a single step, so we'll stick with #1 for now

**Comment by jryhanyc** [comment]
Sounds good @gastaldi just added those to the invision
