### ISSUE TITLE
Evaluate planner list design change

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ux#60]
Now that we have removed the Description field, that list view looks empty. What do you think of this idea? 

Proposed change:
When the Details view appears it "pushes" the list view over so that it is not hidden. This would allow the controls on the list view to be accessed while the Details view is active.

**Comment by mindreeper2420** [comment]
@joshuawilson - it appears empty now due to the fact that the other pieces planned for the list are not in scope ATM. In the long term goals, there is additional information on each item that identify the assigned user, epic, etc.

Another aspect that will come into play more and more are the different screen resolutions. These were designed/defined with a standard screen size, not 1080p (still not industry standard) or 4K.
